JuliaInterop/RCall.jl

src/functions.jl
test/runtests.jl

check the changes, they are self-explained.

allow use of symbols in `lang` and add tests for rcall and @rimport

---

src/RCall.jl
src/sexp.jl

Fix Rf_Scalar bug

---

src/iface.jl

allow parsing unicode code

---

src/RCall.jl
src/sexp.jl

check bounds when getting object from an environment

---

src/library.jl

simplify rwrap function

---

src/sexp.jl

Fixes #39, I think.
I don't really understand the library that well, so @dmbates you should probably check this is correct.

Change sexp tag for real values to 14 (based on Rinternals.h).

---

src/RCall.jl
src/sexp.jl
test/runtests.jl

As title
```julia
using RCall
using RDatasets
mtcars = dataset("datasets", "mtcars");
rmtcars = sexp(mtcars);
rprint(rmtcars)
```

DataFrame to sexp conversion

---

src/RCall.jl

https://github.com/armgong/rcall (r package prototype) is R package embedded julia into R through RCall.jl

patch enable RCall can used in embedded julia 

---

src/RCall.jl
src/iface.jl
src/methods.jl
test/basic.jl

`Rf_PrintValue` can cause segfault if S3 objects has custom print function as it doesn't use `R_tryEval`.

impove rprint function

---

src/RCall.jl
src/eventloop.jl
test/basic.jl

It is an attempt to handle #49. In here, "plot.new" and "grid.newpage" hooks are being used to trigger the loop.

setHook for eventloop

---

src/RCall.jl
src/operators.jl
test/basic.jl

This allows us to do something like
```julia
using RCall
using RDatasets
mtcars = dataset("datasets", "mtcars");
@rlibrary ggplot2
p = ggplot(mtcars, aes_string(x="MPG", y="Disp")) + geom_line();
p
```

add basic opearators

---

.travis.yml
docs/README.md
docs/make.jl
docs/mkdocs.yml

https://github.com/MichaelHatherly/Documenter.jl/issues/1

Rename Lapidary to Documenter.

---

src/eventloop.jl

run R_ProcessEvents on Windows

---

docs/mkdocs.yml
docs/src/gettingstarted.md
src/rstr.jl

I've written a "Getting Started" section for the docs, however I don't understand how they work anymore. @randy3k, can you tell me what else I need to do?

write Getting Started

---

src/rstr.jl

It should fix #107.
@simonbyrne how do you think?

remove temp variables when returned value of @R_str is gc'ed

---

docs/src/gettingstarted.md
docs/src/public.md

See https://github.com/MichaelHatherly/Documenter.jl/pull/51 for details.

Updates for Documenter.jl syntax changes

---

REQUIRE
src/RCall.jl
src/convert-base.jl
src/convert-data.jl
src/eventloop.jl
src/iface.jl
src/io.jl
src/library.jl
src/methods.jl
src/rstr.jl
test/basic.jl
test/conversion.jl

Fix some of the warnings in v0.5

---

src/RCall.jl
src/iface.jl
src/repl.jl
src/setup.jl
test/repl.jl
test/runtests.jl

type `$` (key suggested by Douglas) to activate repl mode and type <kbd>backspace</kbd> to leave r mode
```
R> x=1
R> x
[1] 1
```
close #115

R REPL mode #115

---

src/rstr.jl

Improvement to handle the variable substitution, but it seems that there is an memory leak issue. https://github.com/JuliaStats/RCall.jl/issues/123

evaluating Rstr in globalEnv

---

src/iface.jl
src/repl.jl
src/rstr.jl
test/repl.jl
test/rstr.jl

close #121 
@davidanthoff, please test it.

substituite julia variables in REPL mode

---

src/convert-base.jl
src/eval.jl
src/library.jl
test/runtests.jl

Rearrange reval protect/unprotect

---

src/IJulia.jl

IJulia: don't call InlineDisplay

---

src/eval.jl
src/render.jl
src/repl.jl
test/rstr.jl

use line/col apparch for ascii code

---

docs/src/installation.md
src/setup.jl

Gives a better error message for #143.

Check R library loads when searching.

---

src/convert-data.jl
test/dataframe.jl

Patch the way to convert NullableArrays and improve the corresponding tests.
Fix 164.

Fix 164: patch the way to convert NullableArrays

---

src/convert-data.jl

It solves https://github.com/JuliaInterop/RCall.jl/issues/167
Best

Define sexp for AbstractDataFrame

---

src/io.jl
src/methods.jl
src/repl.jl
test/basic.jl
test/dataframe.jl
test/library.jl
test/repl.jl

Note: this pushes to `0.6` branch instead.

A dozen more v0.6 fixes

---

src/Console.jl
src/RCall.jl
src/RPrompt.jl
src/eval.jl
src/eventloop.jl
src/io.jl
src/setup.jl
test/repl.jl

modularize REPL code

---

src/Console.jl
src/RPrompt.jl
src/eval.jl
src/eventloop.jl
src/io.jl
test/basic.jl

it should be handled by the eventloop
fix #182

rewrite IO code

---

src/convert/default.jl
src/eval.jl
src/io.jl
src/methods.jl
test/basic.jl

It uses `R_do_slot` and `R_do_slot_assign` and also checks for correctness of datatype via the function `methods::checkSlotAssignment`.

getindex and setindex! of S4 objects

---

appveyor.yml
src/setup.jl
test/runtests.jl

Correctly set HOME/R_USER env vars in Windows

---

src/RPrompt.jl
src/eval.jl
src/eventloop.jl
src/io.jl
src/macros.jl
src/render.jl
test/basic.jl
test/render.jl

rewrite `rparse`, `reval`, `render` and REPL code.

a major refactoring of io code

---

src/eval.jl
src/eventloop.jl
src/io.jl
src/render.jl
test/basic.jl

Add a wrapper for R_ToplevelExec to evaluate R_ParseVector.

 use R_ToplevelExec to evaluate R_ParseVector

---

docs/make.jl
docs/src/conversions.md
docs/src/custom.md
src/RCall.jl
src/callback.jl
src/convert/axisarray.jl
src/convert/base.jl
src/convert/categorical.jl
src/convert/dataframe.jl
src/convert/datetime.jl
src/convert/default.jl
src/convert/formula.jl
src/convert/missing.jl
src/macros.jl
src/methods.jl
src/types.jl
test/convert/base.jl
test/macros.jl

Preparing ourself to support R class `JuliaObject`

 allow users to overwrite default conversion rules

---

appveyor.yml

This is an easily updatable script

Use new Appveyor.jl script

---

docs/src/conversions.md
src/convert/base.jl
src/convert/dataframe.jl
src/namespaces.jl

Sanitize symbols imported from R packages

---

src/RPrompt.jl

fix repl mode on julia v1.0

---

.travis.yml
REQUIRE
appveyor.yml
src/RCall.jl
src/setup.jl
test/runtests.jl

Afterward, I will release 0.13.0

drop support of julia 0.7

---

src/callback.jl

don't use Rf_error, return a simpleError instead

---

deps/build.jl

split the error checking for conda R and user R

---

.travis.yml
Project.toml
docs/Project.toml
test/REQUIRE

This file is no longer necessary.

Delete `test/REQUIRE` and fix tests

---

Project.toml
src/io.jl
src/methods.jl
src/setup.jl

working toward the next release.

Release v0.13.6

---

Project.toml

reiterate #370 because #362 is not ready to merge.

upper bound dependencies

---

src/io.jl

use first and last instead

---

Project.toml
src/convert/categorical.jl
src/convert/default.jl

This requires DataFrames 0.21 (not released yet).
Also add upper bounds to all dependencies so that registering new versions
can be automated.

Port to CategoricalArrays 0.8

---

src/convert/datetime.jl
src/convert/default.jl
test/convert/datetime.jl

Allow conversions of Date and DateTime SubArrays

---

src/setup.jl

use detected Rhome

---

Project.toml

Only changes are dependency versions for Missings and DataFrames.
Cc: @bkamins

Bump version to 0.13.11

---

Project.toml

To add support for CategoricalArrays 0.10.

Bump version to 0.13.12

---

src/RCall.jl
src/eval.jl
src/eventloop.jl
src/io.jl
src/setup.jl

Enables ARM support. fixes #440, #385, #325.

remove cfunction closures

---

docs/make.jl
docs/src/gettingstarted.md
docs/src/known-issues.md

Thanks to @adelarue in https://github.com/RcppCore/Rcpp/issues/770#issuecomment-665140387.

Add note on installing packages via Conda

---

docs/README.md

Fix typos in README file

---

.github/workflows/TagBot.yml

Use SSH_KEY as TagBot secret

---

.gitignore
README.md

add Zenodo badge

---

Project.toml
src/RPrompt.jl
test/repl.jl

allow for inline comments in REPL mode

---

Project.toml
src/callback.jl

add deprecated  jtypExtPtrs for backwards compat

---

.github/workflows/docs.yml

This is just in case the fix takes a while.

Pin R version to 4.4 for building docs
