- src/RCall.jl
- src/interface.jl
If an expression contains multiple expressions, we should not only only evaluate the first expression.
```
julia> using RCall
julia> Reval(Rparse("a=1;b=2"))
RCall.SEXP{14}(Ptr{Void} @0x00007fbc8356fcf8)
julia> R.str(Reval(:a))
num 1
RCall.SEXP{0}(Ptr{Void} @0x00007fbc86813b78)
julia> R.str(Reval(:b))
Error: object 'b' not found
```
> patch for multple expressions

- src/interface.jl
It is important when memory of an R object is referenced by a julia variable.
```
using RCall
x = Reval(Rparse("x = 1:10^8"))
RCall.PreserveObject(x)
y = RCall.rawvector(x);
Reval(Rparse("x = 1"))
for(i in 1:10) 
Reval(Rparse("gc()"));
end
y
```
without the `RCall.PreserveObject` statement, the last `y` will produce segfault.
> add ReleaseObject and PreserveObject to protect memory from GC

- src/RCall.jl
see #8 
In v0.4, all converters are constructor, but not in v0.3.
[see here](https://github.com/JuliaLang/julia/blob/2fdaf10d3abf5189d60dc70cd9829e4b9ecfaf76/base/base.jl#L35)
So `Int(1.0)` is fine on v0.4, but not in v0.3.
> patch #8: in v0.3.x, converters are not constructor

- src/RCall.jl
- src/functions.jl
- src/library.jl
A quick example of importing `MASS` and calling `ginv` function.
```
julia> @rimport MASS as m
julia> rcopy(rcall(m.ginv, sexp([1 2;2 4])))
2x2 Array{Float64,2}:
0.04  0.08
0.08  0.16
```
> allow to import an R library as module and call functions in the module

- src/functions.jl
- src/library.jl
as title, in v0.4.x, now it is possible to call the functions directly.
```
julia> @rimport MASS as mass
julia> rcopy(mass.ginv(sexp([1 2;3 4])))
2x2 Array{Float64,2}:
-2.0   1.0
1.5  -0.5
```
> export package contents as LangSxp and make them callable in v0.4.x

- src/sexp.jl
- src/types.jl
1. `sexp(Array{T<:Real,1},)` is ambiguous with `sexp(Array{T<:Bool,N},)`
defining `sexp(Array{Bool,1},)` first would resolve the issue
2. we have to use `unsafe_convert` to convert julia object to a pointer.
> some fixes for v0.4.x

- src/RCall.jl
- src/sexp.jl
As other constants are wrapped by `sexp`, do the same for `unboundValue`.
> to be consistant with other global constants

- src/sexp.jl
- test/runtests.jl
As `rcopy("NA")` returns a string `"NA"`, this dirty fix will work for most cases. But it doesn't differentiate between the real `NA` and the string `"NA"`.
Related to #32
> dirty fix for string array containing NAs

- src/IJulia.jl
- src/RCall.jl
- src/functions.jl
- src/sexp.jl
This adds rudimentary support for IJulia. The rough idea is that before a cell is executed, a new png plot device is created. After the cell has been executed, the plot device is closed, and the resulting file is displayed.
See also discussion in #23.
> Add IJulia plotting support

- src/sexp.jl
- test/runtests.jl
Now, error is thrown when converting factor to `DataArray`. One have to convert it to `PooledDataArray`. The `DataFrame` method is also changed accordingly to use `DataArray` or `PooledDataArray` adaptively.
> throw error when converting a factor to `DataArray`

- src/sexp.jl
- test/runtests.jl
Provide `sexp` methods to DataArray and PooledDataArray objects.
Not ready to be merged.
> DataArray to sexp conversions and some minor code clean

- src/RCall.jl
- src/eventloop.jl
To address issue #49.
There are two major functions. `RCall.rgui_start()` and `RCall.rgui_stop()`. I have only tested it on OSX.
> add eventlooop

- src/IJulia.jl
The use of tempname() on Windows actually creates a .tmp file, and consequently the call to mkpath() fails due to the file already existing. Calling mktempdir() performs the desired operation of creating a temporary directory without this failure occurring on Windows.
> Improve behavior of ijulia_init() on Windows

- src/RCall.jl
- src/methods.jl
- src/rstr.jl
- test/rstr.jl
- test/runtests.jl
See #82.
This is somewhat limited: it only supports ASCII (due to https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16524), and you can't assign to Julia variables (getting that logic correct is a bit complicated). Nevertheless, it seems to work for simple snippets:
```julia
iris = rcopy(:iris)
model =  R"lm(Sepal.Length ~ Sepal.Width,data=$iris)"
```
> R_str macro: allows inlining R code directly into Julia, supporting limited variable substitution.

- REQUIRE
- src/RCall.jl
- src/iface.jl
- src/methods.jl
- src/rstr.jl
This means that we don't need to bother cleaning up after, hence fixing #107 and #109. Also, changes symbol names to be those of the underlying Julia variables, prefixed with `$`, which makes plots look nicer.
> Evaluate R string macro inside own environment.

- src/callback.jl
- src/convert-base.jl
- src/functions.jl
- src/iface.jl
- src/library.jl
- src/operators.jl
- test/basic.jl
- test/rstr.jl
Passes tests under v0.4 and v0.5 and does not produce warnings about `symbol => Symbol` under v0.5
@simonbyrne Can you take a look and pull the trigger if this seems okay?
> symbol(...) => Symbol(...)

- src/macros.jl
- src/render.jl
- src/repl.jl
- test/rstr.jl
use the undocumented `R_ParseContextLast` and `R_ParseContext` to detect parse error.
close #132
> catch error by R_ParseContextLast and R_ParseContext

- .travis.yml
- REQUIRE
- appveyor.yml
- src/RCall.jl
- src/convert-base.jl
- src/convert-data.jl
- src/convert-default.jl
- src/methods.jl
- test/dataframe.jl
- test/rstr.jl
> Update to use NullableArrays and CategoricalArrays

- src/setup.jl
This prevents activation of REPL '$' symbol if julia is being run in a dumb terminal.  This happens if it is run e.g. within emacs (for example. usng julia-mode and ESS)
> Fix: setup should not init '$' REPL if running with basic REPL

- test/dataframe.jl
the behavior of `isnull(Nullable(1, true))` has changed
> fix Nullable test

- test/dataframe.jl
Add test for using R's lm() inside DataFrames' by() (SubDataFrame)
This is an indirect test for (i.e.) `RCall.sexp(sub(attenu,1:10))`
> Add test for using R's lm on SubDataFrame

- REQUIRE
- src/convert-base.jl
- src/eval.jl
- src/io.jl
- src/methods.jl
- src/repl.jl
- src/types.jl
- test/basic.jl
- test/dataframe.jl
- test/library.jl
- test/repl.jl
I have made several changes to the 0.6 branch, the code is now compatible with both v0.5 and v0.6.
The REPL mode on v0.6 is still broken, but a [patch][1] is submitted to julia.
It will be merged into master once the tests pass.
[1]: https://github.com/JuliaLang/julia/pull/21027
> v0.6 compatibility

- src/convert/dataframe.jl
- test/basic.jl
e.g. rcopy(R"factor(rep(1,10))"). Error due to rcopy(Array,
getattrib(s,Const.LevelsSymbol)) returning string type when importing
factor vector of repeated single level. the string is passed to
PooledDataArray constructor, which expects an array and throws error.
Fixed by enforcing Array type using rcopy(Array, getattribs(...))
> Fixes error when importing vector of invariant factor to Julia

- src/convert/base.jl
- src/convert/datetime.jl
- src/convert/default.jl
- src/methods.jl
- test/basic.jl
close #138 
An example of usage can be found in [datatime.jl][1].
@richardreeve, I guess you may be interested in it.
[1]: https://github.com/JuliaInterop/RCall.jl/blob/948e1fd1d95304a78ad01150ce08389b56ed6da0/src/convert/datetime.jl
> Implement of the RClass idea

- REQUIRE
- deps/build.jl
- deps/setup.jl
- docs/src/installation.md
- src/RCall.jl
- src/setup.jl
This is an alternative to #228.  It is a somewhat more comprehensive change that:
* Moves libR detection to the `Pkg.build` stage.
* Auto-installs R via Conda if it is not found.
* Remembers the libR location on subsequent builds (unless you set the `R_HOME` environment variable to override) so that you only have to configure it correctly once.
One question I had was which Conda channel to use.  There is [r-base in the r channel](https://anaconda.org/r/r-base) and [r-base in the conda-forge channel](https://anaconda.org/conda-forge/r-base).   Right now I'm using ~~conda-forge~~ `r`, but I'm not sure if there is a preference.
close #73
> move libR detection to Pkg.build, support Conda installation

- REQUIRE
- src/RCall.jl
- src/convert/formula.jl
The representation of Formulas has changed in StatsModels.  It now holds onto the whole formula expression (e.g., `Expr(:call, :~, ...)`) as well as the parsed expression and the left- and right-hand sub-expressions.
For copying from R to Julia, it's necessary to invoke the `@formula` model to trigger parsing of the formula expression. (That's not strictly true in this release, since it's just transforming the Expr, but it will be in the future to support things like arbitrary functions in formulae).
For Julia to R, in order to match the old behavior, I propose just copying the Expr of the original (un-parsed) formula (in the `ex_orig` field).  There are some situations (where the Formula is constructed manually from left and right-hand sub expressions) that the `ex_orig` field is an …
> update formula copying to StatsModels v0.2.4

- src/callback.jl
Wrap immutable objects in a Ref to avoid the jl_value_ptr problems
> Don't use jl_value_ptr

- .appveyor.yml
- .travis.yml
- src/setup.jl
> Fix for C stack checking issues on 1.1

- src/convert/axisarray.jl
This is mentioned in the Requires.jl docs
Fixes #300 (I hope).
> prefix AxisArrays with .

- deps/build.jl
Hi there, seems like #297 didn't quite get fixed by #299. Unless I'm missing something the variable `different` remains undefined in the revised version. I ran into this problem when trying to install RCall via Conda.
> reinsert `different` info message

- .gitignore
- Project.toml
- src/RCall.jl
- src/convert/default.jl
- src/convert/formula.jl
- test/convert/formula.jl
Currently some of the tests are broken because the `StatsModels.@formula` macro does not preserve the original expression passed to it.  The test could be changed to compare, e.g.
```
RObject(@formula y ~ (a + b) * c)
```
to
```
R"y ~ a + b + c + a:b + b:c"
```
which would look a little peculiar or, my preferred solution, create an `exorig` field in a `FormulaTerm` like that in a `FunctionTerm`.  @kleinschmidt prefers not to do that.  See discussion in #306
> Formula transfer updated to StatsModels v0.6.0

- src/convert/categorical.jl
- test/convert/categorical.jl
The order of levels in the `refs` field of `CategoricalArray` doesn't necessarily reflect the order of `levels`.
> Fix ordering of factor levels

- src/convert/categorical.jl
Currently, only `CategoricalArray{String}` are converted to `factor` correctly. This doesn't work on `master`, but works with this PR.
`CategoricalArray{<:Number}`:
```julia
df_symbol = DataFrame(x = randn(100), y=randn(100), z1=rand([:a; :b], 100), z2=rand([:darkorange; :lightblue], 100))
categorical!(df_symbol, :x)
R"str($df_symbol)" # before: error, after: works as expected
```
`CategoricalArray{Symbol}`:
```julia
df_symbol = DataFrame(x = randn(100), y=randn(100), z1=rand([:a; :b], 100), z2=rand([:darkorange; :lightblue], 100))
ggplot(df_symbol) + geom_point(aes(x=:x, y=:y, color=:z1)) # doesn't work
ggplot(df_symbol) + geom_point(aes(x=:x, y=:y, color=:z2)) # uses colors "darkred" and "lightblue"
categorical!(df_symbol, :z2)
ggplot(df_symbol) + geom_point(aes(x=:x, y=:y, color=:z2)) …
```
> Improve conversion from CategoricalArray to factor

- docs/src/installation.md
See discussion: https://discourse.julialang.org/t/glibcxx-3-4-26-not-found-in-rcall/29113/9
> Add recent distribution failure handling

- docs/src/gettingstarted.md
Fix a typo in the gettingstarted.md file.
> Typo in docs: micro -> macro

- deps/build.jl
See https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Does-R-use-the-Registry_003f. It would be great if someone with a Windows machine with a non-admin account and R installed could check if
```julia
WinReg.querykey(WinReg.HKEY_CURRENT_USER,
"Software\\R-Core\\R", "InstallPath")
```
returns the installation path.
> Also search for Rhome in HKEY_CURRENT_USER since it's used when users don't have admin rights.

- src/convert/categorical.jl
- test/convert/categorical.jl
Ordered and unordered factors were swapped. Add tests to catch this.
Bug introduced by https://github.com/JuliaInterop/RCall.jl/pull/338.
> Fix conversion of CategoricalArray to factor vs. ordered

- src/setup.jl
Currently, when a .RData file is present in the working directory when RCall is initialized, the RData file is loaded into the R session. This is counterintuitive and can lead to extremely high memory consumption. This patch disables this behavior.
I have only tested it on Linux. As far as I understand, RStart.RestoreAction=0 corresponds to --no-restore, so this behavior was already the default on Windows (enforced by R_SetParams in setup.jl:97)
> use --no-restore flag when initializing R

- src/setup.jl
> workaround Rf_initialize_R in Windows

- README.md
The installation link in the readme seems broken currently; this updated link (no `.html`) seems to work.
> Fix installation link in readme

- src/convert/default.jl
- test/convert/dataframe.jl
Closes #355 
`NA` defaulting to `logical` in R seems weird, but R seems to largely think of this as three-value logic instead of an Option/Union type.:
```R
R> class(NA)
[1] "logical"
```
> add methods for an entire column of missing

- .travis.yml
- deps/build.jl
- test/namespaces.jl
- test/runtests.jl
Fixes #389 
1. Currently, Travis CI does not test the Conda-provided R.
2. Currently, the Conda-provided R is broken on both Linux and macOS (#389).
This pull request fixes and tests the Conda-provided R. Specifically:
1. Build step: When installing R from Conda, require that the version of R is greater than or equal to 3.4.0 AND strictly less than 4.0.0.
2. Build step: Define `RCall.conda_provided_r`, which is `true` if RCall is using the Conda-provided R, and `false` otherwise.
3. Test suite: fix some hard-coded instances of `R` and `Rscript`
4. Test suite: skip  the "namespaces" tests if the R "MASS" package is not installed.
5. Test suite: skip the `R_PPStackTop` test if we are using the Conda-provided R.
6. Travis CI: test both the Conda and non-Conda ways of getting R.
7. Travis CI: …
> Fix and test the Conda-provided R

- README.md
This PR adds the PkgEval badge to the README. (More details [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/README.md).)
Please note: RCall is currently failing on PkgEval. This should be fixed by https://github.com/JuliaInterop/RCall.jl/pull/390
> README: add the official PkgEval badge

- src/convert/default.jl
See lines 219 and 244 of `src/convert/default.jl`:
https://github.com/JuliaInterop/RCall.jl/blob/43794215e48408c770d5ce1285c125e4d5f413c5/src/convert/default.jl#L219-L219
https://github.com/JuliaInterop/RCall.jl/blob/43794215e48408c770d5ce1285c125e4d5f413c5/src/convert/default.jl#L244-L244
The method definition on line 244 is unnecessary, because the same exact method was already defined on line 219.
This pull request deletes line 244.
> Remove a duplicate method definition for `sexpclass(::Missing)`

- Project.toml
- deps/build.jl
On RCall v0.13.8 if `]build RCall` is run a second time it can fail:
```
(@v1.5) pkg> build RCall
Building Conda → `~/.julia/packages/Conda/3rPhK/deps/build.log`
Building RCall → `~/.julia/packages/RCall/Xq1xc/deps/build.log`
┌ Error: Error building `RCall`:
│ ERROR: LoadError: MethodError: no method matching hasfield(::Module, ::Symbol)
│ Closest candidates are:
│   hasfield(!Matched::Type{T}, ::Symbol) where T at reflection.jl:187
│ Stacktrace:
│  [1] top-level scope at /Users/jack/.julia/packages/RCall/Xq1xc/deps/build.jl:22
│  [2] include(::String) at ./client.jl:457
│  [3] top-level scope at none:5
│ in expression starting at /Users/jack/.julia/packages/RCall/Xq1xc/deps/build.jl:11
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/sr …
```
> Fix incorrect function

- src/methods.jl
In Julia 1.7 the following warning is shown when passing dataframes to R:
```julia
┌ Warning: use values(kwargs) and keys(kwargs) instead of kwargs.data and kwargs.itr
│   caller = iterate(x::Base.Pairs{Int64, RCall.ListSxp, Base.OneTo{Int64}, Ptr{RCall.ListSxp}}) at methods.jl:232
└ @ RCall ~/.julia/packages/RCall/iMDW2/src/methods.jl:232
```
This PR implements what is suggested.
> Use values(x) to access x.data

- .gitignore
- src/methods.jl
- test/basic.jl
> Add bounds checking to list

- .github/workflows/ci.yml
- test/runtests.jl
Disable conda_provided_r test - This fails on Win64, but perhaps it is ok to not test, since it is just testing threading in the R installation (not RCall itself).
Also remove x86 windows from CI (Addresses #458)
cc @DilumAluthge @randy3k. I think this may be sufficient to get CI to pass and it is ok to not test 32-bit Windows, which is anyways not a Tier 1 supported Julia platform.
> Make CI green - disable x86 windows and disable PPStack test on win64

- docs/src/installation.md
- the path is outdated, and now we need to append `-cran40`, see https://cloud.r-project.org/bin/linux/ubuntu/
- so I try to add the link to the instruction on CRAN
> fix link for ubuntu R

- src/convert/base.jl
In the current setup, RCall returns a closure in Julia, which means it's hard to know in Julia if something is a function from R. This makes it really hard to workaround things that are weird in R, like is seen in https://github.com/SciML/diffeqr/issues/39. This changes it to use a callable struct instead of a closure in order to allow for dispatching.
> Allow for dispatching on the R functions

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- test/runtests.jl
~The latest CI failures all seem related to a single iffy test that was known to be iffy, tested something that isn't in RCall itself, and was already disabled on Windows. xref #462~
~EDIT:~
~Hmmm, I actually might have an idea what's causing that test to fail. Closing this PR until I've investigated further.~
The fix for the broken test was easy -- check the final stack pointer against the initial stack pointer instead of against 0. I suspect 0 isn't the correct value because of a mixture of various things in R, [ASLR](https://en.wikipedia.org/wiki/Address_space_layout_randomization), and Docker images being essentially a FreeBSD jail / chroot on steroids.
closes #470 
@ViralBShah wanna review since you contributed #462 ?
> Update CI to latest practices and fix broken test

- .github/workflows/ci.yml
- Project.toml
- test/convert/datetime.jl
The `as.character` behavior seems to have been completely removed in R 4.3.
> fix datetime to character conversion

- Project.toml
- deps/build.jl
closes #497 
CI failure seems to be: https://github.com/JuliaLang/julia/issues/50611
> allow installing R 4 via Conda

- Project.toml
- src/RPrompt.jl
The current nightly Julia REPL asserts the type of LineEdit.complete_line
> Fix complete_line for Julia REPL with tab-completion

- .gitignore
- Project.toml
- src/RCall.jl
- src/convert/namedtuple.jl
- src/convert/tuple.jl
- test/convert/namedtuple.jl
- test/convert/tuple.jl
- test/runtests.jl
[JuliaCall](https://github.com/Non-Contradiction/JuliaCall/blob/c05473bea78a0197c639f7e82ab1c6f2e943e1cc/inst/julia/convert.jl#L7-L11) currently commits some type piracy to provide support for tuples:
```julia
function sexp(x ::Tuple)
r = sexp(Array{Any}([x...]))
setattrib!(r, :class, sexp("JuliaTuple"))
r
end
```
This PR upstreams a more efficient (and memory safe) approach that avoids the type piracy. The type piracy is particularly unfortunate because it breaks [JellyMe4](https://github.com/palday/JellyMe4.jl/issues/72) when used from within JuliaCall. (JuliaCall works by starting Julia and running RCall from the Julia session.)
I also take advantage of the new tuple implementation to simplify the named tuple implementation a bit and potentially make it a bit more efficient.
Finally, I …
> Add support for tuples and better round tripping of named tuples

- docs/src/installation.md
Hello! I've been excited to see the progress on making it possible to use RCall with CondaPkg.
Tried taking it for a spin using the directions in the docs, and I think I've found a typo. Figured I'd make a quick PR in case it is indeed a typo.
> Fix possible typo in docs

- Project.toml
There's nothing in RCall itself that's incompatible with Julia 1.0, but the dependencies for testing are not resolvable on 1.0 and we haven't tested on 1.0 in a while.
> bump Julia compat

- Project.toml
- docs/Project.toml
- docs/src/conversions.md
- src/convert/datetime.jl
- test/convert/datetime.jl
- test/runtests.jl
> allow conversion (with loss of precision) for arbitrary precision POSIXct objects

- src/RPrompt.jl
The `hint` keyword was added to the API of `complete_line`, and a corresponding positional argument was added to `bslash_completions`. This change adds the `hint` keyword to our method of `complete_line` and passes it along to `bslash_completions`, which is defined locally to accept and ignore the `hint` argument for earlier Julia versions.
> Fix REPL issue on Julia nightly

- src/convert/axisarray.jl
- src/convert/base.jl
- src/methods.jl
~closes # 431~
apparently not on Mac
> safer indexing for AbstractArray

- Project.toml
- src/RCall.jl
- src/ijulia.jl
- src/macros.jl
- test/.gitignore
- test/ijulia.jl
- test/ijulia.jmd
- test/runtests.jl
> IJulia docstrings + tests

- .github/workflows/ci.yml
Separating from https://github.com/JuliaInterop/RCall.jl/pull/562
> Pin most recent R release at 4.4 in CI

- src/io.jl
This method definition suppresses the stacktrace for all `RException` exceptions. Can we remove this so that it's easier to determine where an error comes from if there are e.g. lots of `revals` or `R_str`s?
> Remove RException showerror method which supresses backtraces

- Project.toml
- ext/RCallAxisArraysExt.jl
- src/RCall.jl
- src/setup.jl
AxisArrays interoperability was the only use of Requires and is otherwise completely separable from the rest of the package code, making it an ideal candidate for a package extension.
> Move AxisArrays to an extension, drop Requires dependency

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- Project.toml
- README.md
- docs/README.md
- src/convert/base.jl
- src/methods.jl
- test/convert/base.jl
- test/runtests.jl
R 4.5 introduced a few changes that break RCall:
- stricter internal vs. external API boundaries, which we felt with our call to `SET_SYMVALUE`
- apparently an optimization to the way empty vectors are stored, which broke our handling of them by messing up pointer alignment (at least on x86-64)
Failures on nightly are unrelated: #565
closes #561
> use public API `Rf_defineVar` instead of internal `SET_SYMVALUE`

- Project.toml
- src/namespaces.jl
The previous version included an `eval`. 🤔
> improve hygiene of rimport macro
